services:
  postgres:
    image: postgres:latest
    container_name: postgres_main
    environment:
      POSTGRES_USER: akunamatata
      POSTGRES_PASSWORD: Sobol15951
      POSTGRES_DB: postgres_main_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
    command: >
      postgres -c max_connections=300
               -c shared_buffers=128MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U akunamatata -d postgres_main_db"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

volumes:
  pgdata:
    driver: local

networks:
  app-network:
