spring:
  web:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres_main_db
    username: akunamatata
    password: Sobol15951
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    login:
      loginPage: "/login"
      logoutPage: "/logout"
    swagger:
      swaggerUri: "/swagger-ui/**"
      apiDocsUri: "/v3/api-docs/**"
    jwt:
      secretKey: #secret #todo change key
      keyCryptoAlgorithm: "HmacSHA256"
      jwtAlgorithm: "HS256"
      expirationTime: 2 #in hours
    oauth2:
      loginPage: "/login"
      defaultSuccessPage: "/v1/home"
      failureLoginPage: "/v1/auth/login?error"
      client:
        registration:
          github:
            client-id: #secret #todo hide api keys and ids
            client-secret: #secret
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/v1/auth/login/oauth2/code/github"
            client-name: GitHub
          google:
            client-id: #secret
            client-secret: #secret
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/v1/auth/login/oauth2/code/google"
            client-name: Google

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8088

logging:
  file:
    name: "authlogs.log"
  level:
    org.springframework.security: TRACE
    root: INFO